# Scripture Memory and Meditation

## Why Scripture Memory.

Ephesians 6:17. The Sword of the Spirit. We are in a war, and the Scripture we have in our heart is the ammunition.

Imagine facing a decision and needing to find guidance. When the Holy Spirit looks for weapons, all He finds is John 3:16 and a few of the commandments memorized in the wrong order.

### Is it necessary?

Psalms 119:9-16; 23-24 - Benefits of meditating on Scripture

1 Peter 3:15 - Witnessing.

How did it help the men of the bible?

1. Jesus - Matthew 4:1-11 - Jesus speaking with the evil one  
2. Peter - Acts 2:14-40 - Peter preaching after the Pentecost  
3. Moses - Numbers 14:17-20  

### How to memorise scripture?

1. Have a plan.  
2. Speak aloud and write out the verse  
3. Memorise the verse word perfect.  
4. Avoid excuses.  

   a. I have bad memory. What if I offered you 1000 Ksh. for every word.  
   b. I am too busy. A man was able to memorize while on the job.  
   c. If I memorize too many, I may become proud.  

5. Be disciplined. Better is a man who rules his spirit than one who takes over a nation.
6. Find an accountability partner.
7. Revise and meditate daily. What is measured, grows.

However, scripture memory alone is not what will save. The Pharisees also
memorized scripture and quoted it to Jesus. Satan also memorized scripture. 