# Meditation  

Meditation is deep unrushed thinking about the truths revealed in Scripture in order to **understand, believe, and apply** them in our lives.  

Joshua 1:8  
Psalms 1:1-3  
Psalms 119:97-100  

Oh, how I love your instructions! I think about them all day long. Your commands make me wiser than my enemies, for they are my constant guide. Yes, I have more insight than my teachers, for I am always thinking of your laws.I am even wiser than my elders, for I have kept your commandments.  

Rewriting a verse in your own words can really help you put into words the thoughts you have.  

## How to Meditate on scripture.  

1. Select and rewrite the verse that you are studying.
2. Write out the message of the verse.
3. Look at the context of the verse
4. Write down questions that arise from the verse.
5. Application. Ask God to show you how to apply the verse to your life.
6. Proof of memory. Try and memorize the verse.
7. Sharing with people. Whenever you speak with someone, encourage them with what you are learning.

